const Discord = require('discord.js');
const colours = require("../../JSON Files/colours.json");
const paginationEmbed = require('discord.js-pagination');
module.exports = {
    name: "jserrors",
    category: "JavaScript",
    description: "Errors within the javascript library",
    run: async (client, message, args) => {
    let _1 = new Discord.MessageEmbed()
    .setAuthor("Errors Within In The JavaScript Library", "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png")
    .setDescription("[`Error: Permission denied to access property \"x\"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied)\n[`InternalError: too much recursion`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Too_much_recursion)\n[`RangeError: argument is not a valid code point`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_codepoint)\n[`RangeError: invalid array length`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length)\n[`RangeError: invalid date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_date)\n[`RangeError: precision is out of range`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Precision_range)\n[`RangeError: radix must be an integer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_radix)\n[`RangeError: repeat count must be less than infinity`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Resulting_string_too_large)")
    .setColor(colours.JS)
    let _2 = new Discord.MessageEmbed()
    .setAuthor("Errors Within In The JavaScript Library", "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png")
    .setDescription("[`ReferenceError: \"x\" is not defined`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined)\n[`ReferenceError: assignment to undeclared variable \"x\"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Undeclared_var)\n[`ReferenceError: can't access lexical declaration 'X' before initialization`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_lexical_declaration_before_init)\n[`ReferenceError: deprecated caller or arguments usage`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_caller_or_arguments_usage)\n[`ReferenceError: invalid assignment left-hand side`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_assignment_left-hand_side)\n[`ReferenceError: reference to undefined property \"x\"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Undefined_prop)\n[`SyntaxError: \"0\"-prefixed octal literals and octal escape seq. are deprecated`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_octal)")
    .setColor(colours.JS)
    let _3 = new Discord.MessageEmbed()
    .setAuthor("Errors Within In The JavaScript Library", "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png")
    .setDescription("[`SyntaxError: \"use strict\" not allowed in function with non-simple parameters`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Strict_Non_Simple_Params)\n[`SyntaxError: \"x\" is a reserved identifier`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Reserved_identifier)[`SyntaxError: JSON.parse: bad parsing`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/JSON_bad_parse)\n[`SyntaxError: Malformed formal parameter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Malformed_formal_parameter)\n[`SyntaxError: Unexpected token`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_token)\n[`SyntaxError: Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_source_map_pragma)\n[`SyntaxError: a declaration in the head of a for-of loop can't have an initializer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_for-of_initializer)\n[`SyntaxError: applying the 'delete' operator to an unqualified name is deprecated`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Delete_in_strict_mode)")
    .setColor(colours.JS)
    let _4 = new Discord.MessageEmbed()
    .setAuthor("Errors Within In The JavaScript Library", "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png")
    .setDescription("[`SyntaxError: for-in loop head declarations may not have initializers`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_for-in_initializer)\n[`SyntaxError: function statement requires a name`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unnamed_function_statement)\n[`SyntaxError: identifier starts immediately after numeric literal`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Identifier_after_number)\n[`SyntaxError: illegal character`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Illegal_character)\n[`SyntaxError: invalid regular expression flag \"x\"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_regexp_flag)\n[`SyntaxError: missing ) after argument list`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_parenthesis_after_argument_list)\n[`SyntaxError: missing ) after condition`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_parenthesis_after_condition)\n[`SyntaxError: missing : after property id`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_colon_after_property_id)")
    .setColor(colours.JS)
    let _5 = new Discord.MessageEmbed()
    .setAuthor("Errors Within In The JavaScript Library", "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png")
    .setDescription("[`SyntaxError: missing ; before statement`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_semicolon_before_statement)\n[`SyntaxError: missing = in const declaration`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_initializer_in_const)\n[`SyntaxError: missing ] after element list`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_bracket_after_list)\n[`SyntaxError: missing formal parameter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_formal_parameter)\n[`SyntaxError: missing name after . operator`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_name_after_dot_operator)\n[`SyntaxError: missing variable name`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/No_variable_name)\n[`SyntaxError: missing } after function body`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_curly_after_function_body)\n[`SyntaxError: missing } after property list`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Missing_curly_after_property_list)")
    .setColor(colours.JS)
    let _6 = new Discord.MessageEmbed()
    .setAuthor("Errors Within In The JavaScript Library", "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png")
    .setDescription("[`SyntaxError: redeclaration of formal parameter \"x\"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Redeclared_parameter)\n[`SyntaxError: return not in function`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_return_or_yield)\n[`SyntaxError: test for equality (==) mistyped as assignment (=)?`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Equal_as_assign)\n[`SyntaxError: unterminated string literal`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unterminated_string_literal)\n[`TypeError: \"x\" has no properties`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/No_properties)\n[`TypeError: \"x\" is (not) \"y\"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type)\n[`TypeError: \"x\" is not a constructor`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_constructor)\n[`TypeError: \"x\" is not a function`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_function)")
    .setColor(colours.JS)
    let _7 = new Discord.MessageEmbed()
    .setAuthor("Errors Within In The JavaScript Library", "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png")
    .setDescription("[`TypeError: \"x\" is not a non-null object`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/No_non-null_object)\n[`TypeError: \"x\" is read-only`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Read-only)\n[`TypeError: 'x' is not iterable`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/is_not_iterable)\n[`TypeError: More arguments needed`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/More_arguments_needed)\n[`TypeError: Reduce of empty array with no initial value`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Reduce_of_empty_array_with_no_initial_value)\n[`TypeError: X.prototype.y called on incompatible type`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Called_on_incompatible_type)\n[`TypeError: can't access dead object`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object)\n[`TypeError: can't access property \"x\" of \"y\"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_access_property)")
    .setColor(colours.JS)
    let _8 = new Discord.MessageEmbed()
    .setAuthor("Errors Within In The JavaScript Library", "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png")
    .setDescription("[`TypeError: can't assign to property \"x\" on \"y\": not an object`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_assign_to_property)\n[`TypeError: can't define property \"x\": \"obj\" is not extensible`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_define_property_object_not_extensible)\n[`TypeError: can't delete non-configurable array element`](TypeError: can't delete non-configurable array element)\n[`TypeError: can't redefine non-configurable property \"x\"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_redefine_property)\n[`TypeError: cannot use 'in' operator to search for 'x' in 'y'`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/in_operator_no_object)\n[`TypeError: cyclic object value`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value)\n[`TypeError: invalid 'instanceof' operand 'x'`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/invalid_right_hand_side_instanceof_operand)\n[`TypeError: invalid Array.prototype.sort argument`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Array_sort_argument)")
    .setColor(colours.JS)
    let _9 = new Discord.MessageEmbed()
    .setAuthor("Errors Within In The JavaScript Library", "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png")
    .setDescription("[`TypeError: invalid arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Typed_array_invalid_arguments)\n[`TypeError: invalid assignment to const \"x\"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_const_assignment)\n[`TypeError: property -\"x\" is non-configurable and can't be deleted`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cant_delete)\n[`TypeError: setting getter-only property \"x\"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Getter_only)\n[`TypeError: variable \"x\" redeclares argument`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Var_hides_argument)\n[`URIError: malformed URI sequence`](URIError: malformed URI sequence)\n[`Warning: -file- is being assigned a //# sourceMappingURL, but already has one`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Already_has_pragma)\n[`Warning: 08/09 is not a legal ECMA-262 octal constant`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Bad_octal)\n[`Warning: Date.prototype.toLocaleFormat is deprecated`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_toLocaleFormat)\n[`Warning: JavaScript 1.6's for-each-in loops are deprecated`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/For-each-in_loops_are_deprecated)\n[`Warning: String.x is deprecated; use String.prototype.x instead`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_String_generics)\n[`Warning: expression closures are deprecated`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_expression_closures)\n[`Warning: unreachable code after return statement`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Stmt_after_return)")
    .setColor(colours.JS)
    const pages = [    
        _1,
        _2,
        _3,
        _4,
        _5,
        _6,
        _7,
        _8,
        _9,
    ];

    const emojiList = ['⏪', '⏩']

    const timeout = '1200000';

    paginationEmbed(message, pages, emojiList, timeout);
}}